// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSMbXXoONc8Y1vygJ3BWtVczH7_RdNNHU',
    appId: '1:462845774640:web:ae9265d8cf08be1926d6f5',
    messagingSenderId: '462845774640',
    projectId: 'rising-distributor-44cb3',
    authDomain: 'rising-distributor-44cb3.firebaseapp.com',
    storageBucket: 'rising-distributor-44cb3.firebasestorage.app',
    measurementId: 'G-F0E8KLSFNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBytVjMcfNK5s-S54nT15AKrzbyAI6be-U',
    appId: '1:462845774640:android:07d3f2915592ce0226d6f5',
    messagingSenderId: '462845774640',
    projectId: 'rising-distributor-44cb3',
    storageBucket: 'rising-distributor-44cb3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz1hqR4hzGwvOsIrPlbxJmNW71STjTGo8',
    appId: '1:462845774640:ios:54cf803cccae40f626d6f5',
    messagingSenderId: '462845774640',
    projectId: 'rising-distributor-44cb3',
    storageBucket: 'rising-distributor-44cb3.firebasestorage.app',
    iosBundleId: 'com.rising.raisingIndia',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz1hqR4hzGwvOsIrPlbxJmNW71STjTGo8',
    appId: '1:462845774640:ios:9cf0c006eaed6ad926d6f5',
    messagingSenderId: '462845774640',
    projectId: 'rising-distributor-44cb3',
    storageBucket: 'rising-distributor-44cb3.firebasestorage.app',
    iosBundleId: 'com.example.raisingIndia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSMbXXoONc8Y1vygJ3BWtVczH7_RdNNHU',
    appId: '1:462845774640:web:68b233086cbac02526d6f5',
    messagingSenderId: '462845774640',
    projectId: 'rising-distributor-44cb3',
    authDomain: 'rising-distributor-44cb3.firebaseapp.com',
    storageBucket: 'rising-distributor-44cb3.firebasestorage.app',
    measurementId: 'G-Q9H2VJE9KY',
  );
}
